project:
  type: website
  output-dir: docs
  
website:
  title: "Luke Andrade's Portfolio"
  navbar:
    background: black
    foreground: white
    left:
      - href: index.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
      #- href: books.qmd
       # text: Reading List

    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/landrade0228/
      - icon: github
        href: https://github.com/StochasticSorcerer
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Luke Andrade"

format:
  html:
    fontcolor: black
    linkcolor: black
    toc: true

css: styles.css

editor: source

