project:
  type: website
  output-dir: docs
  
website:
  title: "Luke Andrade Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/landrade0228/
      - icon: github
        href: https://github.com/StochasticSorcerer/quarto-website-template
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Luke Andrade"

format:
  html:
    theme: cerulean
    toc: true

editor: source

