---
title: "Reading List"
---

## *Technical*

#### All the Math you Missed (But Need to Know for Graduate School) <br> *Thomas A Garrity*

This book briefly covers key concepts, definitions, and theorem for 20 different subjects.

#### Understanding Analysis <br> *Stephen Abbott*

Currently reading this in preparation for measure theoretic probability and statistics in grad school.

#### Stochastic Calculus for Finance I: The Binomial Asset Pricing Model <br> *Steven E. Shreve*

Currently reading this to learn about stochastic calculus.

#### Stochastic Calculus for Finance II: Continuous-Time Model <br> *Steven E. Shreve*

Plan to read this after the first book.

## *Novel Series*

#### Re:Zero - Starting Life in Another World

Currently on Volume 21

Series about an average 18 year old who gets sent to another world but every time he dies, which happens a lot, he gets sent back in time to try again but there is a catch. He is unable to tell anyone about his power and he can't control it either.

#### No Game No Life

Currently on Volume 11

Series about a bother and sister gaming duo who get sent to another world where violence is prohibited (literally impossible) and all affairs are conducted through games.

#### Future Series

**Is it Wrong to Try to Pick up Girls in a Dungeon**

The name is definitely misleading. It's about a fantasy world where the characters go into a dungeon to get loot and level up by slaying monsters. The main character gets saved by a high level adventurer when a high level monster ended up in a low level floor. He then strives to become stronger to reach her level.

**Mushoku Tensei - Jobless Reincarnation**

Not entirely sure what its about yet.